[project]
name = "lesson20"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hardtanh", email = "fcdjin@hardtanh.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.26.0,<1",
    "ipykernel>=7.3.0",
    "numpy>=1.26.4,<2",
    "tiktoken>=0.13.0",
    "torch>=2.2.2",
    "torchaudio>=2.2.2",
    "torchvision>=0.17.2",
    "transformers>=4.51.0,<5",
]

[project.scripts]
lesson20 = "lesson20:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'"
]
